version: "3"

services:
  web:
    image: nginxdemos/hello
    networks:
      - traefik_proxy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:hello.ufgd"
        - "traefik.port=80"
    
networks:
  traefik_proxy:
    external:
      name: traefik_proxy