version: "3"

services:
  proxy:
    image: traefik:alpine
    command: "traefik --docker --docker.swarmmode --docker.watch --api --debug"
    ports:
      - 80:80
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  proxy: